module.exports = {
  someSidebar: [
    {
      type: 'doc',
      id: 'home-doc',
      label: 'Documentation',
    },
    {
      type: 'category',
      label: 'Lendiom Pay',
      collapsed: false,
      items: [
        'pay/what-is-pay',
        'pay/logging-in',
        {
            type: 'category',
            label: 'Guides',
            items: [
              {
                type: 'autogenerated',
                dirName: 'pay/guides',
              },
            ],
          },
      ],
    },
    {
      type: 'category',
      label: 'Lendiom App',
      collapsed: false,
      items:
      [
        'app/what-is-lendiom',
        'app/getting-started',
        'app/communication',
        'app/faq',
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'app/guides',
            },
          ],
        },
        {
          type: 'category',
          label: 'How it Works',
          items: [
            {
              type: 'autogenerated',
              dirName: 'app/how-it-works'
            }
          ]
        },
        {
          type: 'category',
          label: 'Payment Processing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'app/payment-processing'
            }
          ]
        },
      ],
    }
  ],
};
