module.exports = {
  someSidebar: [
    {
      type: 'doc',
      id: 'doc1',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Lendiom Pay',
      collapsed: false,
      items: [
        'pay/what-is-it',
      ],
    },
    {
      type: 'category',
      label: 'Lendiom App',
      collapsed: true,
      items: 
      [
        'app/what-is-it',
        {
          type: 'category',
          label: 'Variables',
          items: [
            {
              type: 'autogenerated',
              dirName: 'app/variables',
            }
          ],
        },
      ],
    }
  ],
};
