name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 18.16.0

      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Client
        run: |
          yarn install
          yarn run build

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lendiom-docs .

      - name: Run Docker image
        run: docker run -d -p 5005:5005 lendiom-docs
